# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u1_nickname', models.CharField(max_length=30)),
                ('u2_nickname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='friendrelation',
            name='u1_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u1_group', to='Chat.Group'),
        ),
        migrations.AddField(
            model_name='friendrelation',
            name='u1_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u1_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendrelation',
            name='u2_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u2_group', to='Chat.Group'),
        ),
        migrations.AddField(
            model_name='friendrelation',
            name='u2_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u2_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('group_name', 'username')]),
        ),
        migrations.AlterUniqueTogether(
            name='friendrelation',
            unique_together=set([('u1_name', 'u2_name')]),
        ),
    ]
