# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrelation',
            name='u1_nickname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='friendrelation',
            name='u2_nickname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
