# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_auto_20160607_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='state',
            field=models.CharField(choices=[('T', 'Online'), ('F', 'Offline')], max_length=2),
        ),
    ]
