# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_auto_20160607_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Unknown')], max_length=2),
        ),
    ]
