# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_auto_20160607_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
