# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0010_auto_20160608_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrelation',
            name='last_chat_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
